### ISSUE TITLE
Can't generate receive payment

### ISSUE THREAD

**Issue by jhysum** [ACINQ/eclair#141]
i can't seem to generate receive payment. At every value I put into it it's either "the payment request can not be generated" or once I hit too big of a number it says my amount has to be below x amount of msat.

I've tried it on all 3 settings mili, satoshi, milisatoshi.

I've connected my 3 local instances to each other. I think I'm running the most current eclair code.

last commit was d2d3b58fe77da5b8242e646ad5c1fa4eea47a0c0, aug 17th

**Comment by btcontract** [comment]
Can confirm this. This seems to be a very weird issue because I launch the same `eclair-node-javafx_2.11-0.2-alpha4-c85823f-capsule-fat` jar and some running instances do create payment requests while others display "The payment request could not be generated" error message.

Eclair.conf of one such failing instance:

```
eclair {
	server {
		public-ips = ["127.0.0.1"]
		binding-ip = "0.0.0.0"
		port = 48002

		api {
			binding-ip = "127.0.0.1"
    			port = 8082
		}
	}

	node-alias="Eclair-B"
}

```

**Comment by pm47** [comment]
I'm not able to reproduce on master at HEAD.

@jhysum what branch where you on? I can't seem to find the commit number you provided

**Comment by jhysum** [comment]
<img width="978" alt="screen shot 2017-08-25 at 6 49 00 pm" src="https://user-images.githubusercontent.com/1687131/29712874-34dc354e-89c6-11e7-92aa-2691a254554d.png">

**Comment by jhysum** [comment]
@pm47 not sure if that image helps but I'm also working off of a fork version of eclair. The fork version doesn't do much but change it to point to a different btc based coin. and also some renameing of strings.

**Comment by pm47** [comment]
Ok, this explains the unknown commit number it is 3e81fce898368835ac48f5c273f905dbe9716d3d on our branch.

**Comment by jhysum** [comment]
haha yeah I completely forgot that it would create new commit numbers.

**Comment by pm47** [comment]
Do you see anything in the logs? (~/.eclair/eclair.log)

**Comment by jhysum** [comment]
Nothing that stood out, I can upload to you my log if you want

**Comment by pm47** [comment]
Yes please, that's better than nothing.

**Comment by jhysum** [comment]
I've uploaded 3 log files from the 3 instances that I've opened. I hope these help.

[eclair.log.txt](https://github.com/ACINQ/eclair/files/1251784/eclair.log.txt)
[eclair2.log.txt](https://github.com/ACINQ/eclair/files/1251788/eclair2.log.txt)
[eclair3.log.txt](https://github.com/ACINQ/eclair/files/1251789/eclair3.log.txt)

**Comment by pm47** [comment]
You haven't override `eclair.payment-handler` conf parameter have you?

@btcontract I mentioned this specific key to you earlier, any chance this might be related?

**Comment by btcontract** [comment]
@pm47 no, I do use one instance which has a custom mongodb payment handler and it generates requests without issues. The ones with problems are vanilla instances without any overrides.

It seems I did just find a possible cause: moving `api` block out of `server` block fixes an issue. Correct config file looks like this now:

```
eclair {
	server {
		public-ips = ["127.0.0.1"]
		binding-ip = "0.0.0.0"
		port = 48010
	}

	api {
		binding-ip = "127.0.0.1"
  	        port = 8082
	}

	node-alias="Eclair-B2"
}
```

I think maybe having an `api` block nested causes Eclair instances to use the same default port and this interferes somehow with request generation (not sure about this).

**Comment by pm47** [comment]
Confirmed! I was able to reproduce with your setting.

This is related to an init issue which has been fixed in #120. You should not be able to launch eclair with the faulty conf now.

@jhysum any chance you can try to reproduce with 4cd081c11c4c08e6f25d48a3487d6bcd9b2475ef?

**Comment by kevinmmarlow** [comment]
@pm47 I rebased and cherry-picked. Still getting the same error. Channel opens, state goes to NORMAL, try to receive a payment with an amount lower than maximum of channel, get the following in red letters when clicking generate.

"The payment request could not be generated."

**Comment by pm47** [comment]
Did you cherry-pick 43d6c80f9ef813686e95b75ef07afddb67d3bedc or 4cd081c11c4c08e6f25d48a3487d6bcd9b2475ef?

Issue has been fixed in 43d6c80f9ef813686e95b75ef07afddb67d3bedc, 4cd081c11c4c08e6f25d48a3487d6bcd9b2475ef is the HEAD, I thought you would just merge. Sorry if I was not clear.

**Comment by kevinmmarlow** [comment]
@pm47 Yes, I did the cherry-pick. Although it looks like I wasn't able to build the newest javafx jar in the `eclair-node-javafx` directory using `mvn package -DskipTests -Pinstaller`. I turned on logging in the `logback.xml` file and ran the jar generated in `eclair-node-gui/target/jfx/app/eclair-node-gui_2.11-0.2-SNAPSHOT-jfx.jar`.

I see all of the logs, yet I don't see the log I added in the `ReceivePaymentController`. It is also not showing the log in the `eclair.log` file in the datadir. Here is the relevant code.

```
if (GUIValidators.validate(amountError, "Amount must be greater than 0", smartAmount.amount > 0)
  && GUIValidators.validate(amountError, f"Amount must be less than ${PaymentRequest.maxAmount.amount}%,d msat (~${PaymentRequest.maxAmount.amount / 1e11}%.3f VIA)", smartAmount < PaymentRequest.maxAmount)
  && GUIValidators.validate(amountError, "Description is too long, max 256 chars.", description.getText().size < 256)) {
  import scala.concurrent.ExecutionContext.Implicits.global
  handlers.receive(smartAmount, description.getText) onComplete {
    case Success(s) =>
      Try(createQRCode(s)) match {
        case Success(wImage) => displayPaymentRequest(s, Some(wImage))
        case Failure(t) => displayPaymentRequest(s, None)
      }
    case Failure(t) => Platform.runLater(new Runnable {
      logger.debug(s"The payment request could not be generated: ${t.getMessage}")
      def run = GUIValidators.validate(amountError, "The payment request could not be generated", false)
    })
  }
}
```

**Comment by jhysum** [comment]
k I just pulled from the lastest master and rebased and it didn't work still. I'll upload more logs later today.

I was wondering if our current config setup has anything to do with it. I'm testing locally and on mainnet. I'll upload my ref file and config file now.

[eclair.conf.txt](https://github.com/ACINQ/eclair/files/1253404/eclair.conf.txt)
[eclair.log.txt](https://github.com/ACINQ/eclair/files/1253405/eclair.log.txt)
[reference.conf.txt](https://github.com/ACINQ/eclair/files/1253406/reference.conf.txt)

I'm testing with viacoin and not sure if it's something we messed up.

**Comment by pm47** [comment]
@jhysum @kevinmmarlow Guys let me get this straight: not only are you working on a (private?) fork, but it is not even for bitcoin? Don't you think that is something you should have mentioned right away?

I would love to help you, but Eclair is still in alpha, under heavy development and we just don't have the resources to support multiple forks for multiple blockchains.

So please help me first and try to reproduce this issue with the vanilla eclair, *from our current main branch, on bitcoin regtest or testnet*. If you can reproduce it, I'll be able to fix it and you will benefit from the fix, otherwise then the bug probably comes from your modification.

Thanks!

@btcontract: did you have time to try and reproduce with our current master branch?

**Comment by btcontract** [comment]
@pm47 Yes, no such issue on master branch. Eclair now refuses to launch when the same port is already taken so this mitigates an issue I think.

**Comment by pm47** [comment]
Thanks Anton, let's wait for the OP's response but I think we are good.

**Comment by jhysum** [comment]
Hey guys, sorry for not specifying the above earlier. I'll try to test this on bitcoin itself after I've downloaded the full core and I'll definitely see if it's something on our side( most likely is) and get back to you guys. Thanks for all the help and you guys are doing an awesome job!
